# Generated by Django 3.0.3 on 2020-03-08 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='group_user',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='group_user',
            name='group',
        ),
        migrations.RemoveField(
            model_name='group_user',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='payment_individual',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='payment_individual',
            name='lender',
        ),
        migrations.RemoveField(
            model_name='payment_individual',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='payment_whole',
            name='group',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='lender',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Group_User',
        ),
        migrations.DeleteModel(
            name='Payment_Individual',
        ),
        migrations.DeleteModel(
            name='Payment_Whole',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
