# Generated by Django 3.0.3 on 2020-02-20 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_user',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='group_user',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='group_user',
            unique_together={('user', 'group')},
        ),
    ]
