# Generated by Django 3.0.4 on 2020-04-17 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20200320_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('total_amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lended_amount', models.FloatField()),
                ('status', models.CharField(max_length=1)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BorrowerNew', to=settings.AUTH_USER_MODEL)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='LenderNew', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
