# Generated by Django 3.0.4 on 2020-04-17 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_payment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_user',
            old_name='status',
            new_name='done',
        ),
    ]
