# Generated by Django 3.0.4 on 2020-04-17 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200417_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_user',
            old_name='done',
            new_name='status',
        ),
    ]
